// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UltraSol.Modules.Pricing.Infrastructure.Persistence;

#nullable disable

namespace UltraSol.Modules.Pricing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260919045749_AllowUnattributedPricingAudit")]
    partial class AllowUnattributedPricingAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UltraSol.Modules.Pricing.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("ActivatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("activated_by");

                    b.Property<string>("CommercialTerms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commercial_terms");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_at");

                    b.Property<Guid?>("TerminatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("terminated_by");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId")
                        .IsUnique();

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("contracts", "pricing");
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Domain.Negotiations.NegotiatedPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<Guid?>("ProposedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_by");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("rejected_by");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("SkuId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("CustomerId", "Status");

                    b.ToTable("negotiated_prices", "pricing");
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Domain.PriceLists.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("price_lists", "pricing");
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Domain.Prices.SkuPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("_lastMutationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_mutation_at");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("PriceListId", "SkuId")
                        .IsUnique();

                    b.ToTable("sku_prices", "pricing");
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.ContractPriceAmendmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("ProposalJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("proposal_json");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<Guid>("SkuPriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_price_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("SkuPriceId", "ProposedAt");

                    b.ToTable("contract_price_amendments", "pricing");
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.PriceChangeRow", b =>
                {
                    b.Property<Guid>("SkuPriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_price_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<Guid?>("ContractPriceAmendmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_price_amendment_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("SkuPriceId", "Revision");

                    b.ToTable("price_changes", "pricing");
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.PricePeriodRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContractPriceAmendmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_price_amendment_id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("SkuPriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_price_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractPriceAmendmentId");

                    b.HasIndex("SkuPriceId", "EffectiveFrom");

                    b.ToTable("price_periods", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_price_periods_range", "effective_to IS NULL OR effective_to > effective_from");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.PriceTierRow", b =>
                {
                    b.Property<Guid>("PricePeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_period_id");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_quantity");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.HasKey("PricePeriodId", "MinimumQuantity");

                    b.ToTable("price_tiers", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_price_tiers_values", "minimum_quantity > 0 AND amount >= 0");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Domain.Contracts.Contract", b =>
                {
                    b.HasOne("UltraSol.Modules.Pricing.Domain.PriceLists.PriceList", null)
                        .WithMany()
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("UltraSol.Modules.Pricing.Domain.ValueObjects.EffectivePeriod", "Validity", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.Property<DateTimeOffset?>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_to");

                            b1.HasKey("ContractId");

                            b1.ToTable("contracts", "pricing");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.Navigation("Validity")
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Domain.Negotiations.NegotiatedPrice", b =>
                {
                    b.HasOne("UltraSol.Modules.Pricing.Domain.Contracts.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("UltraSol.Modules.Pricing.Domain.ValueObjects.EffectivePeriod", "Validity", b1 =>
                        {
                            b1.Property<Guid>("NegotiatedPriceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.Property<DateTimeOffset?>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_to");

                            b1.HasKey("NegotiatedPriceId");

                            b1.ToTable("negotiated_prices", "pricing");

                            b1.WithOwner()
                                .HasForeignKey("NegotiatedPriceId");
                        });

                    b.Navigation("Validity")
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Domain.Prices.SkuPrice", b =>
                {
                    b.HasOne("UltraSol.Modules.Pricing.Domain.Contracts.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UltraSol.Modules.Pricing.Domain.PriceLists.PriceList", null)
                        .WithMany()
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.ContractPriceAmendmentRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Pricing.Domain.Contracts.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Pricing.Domain.Prices.SkuPrice", null)
                        .WithMany()
                        .HasForeignKey("SkuPriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.PriceChangeRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Pricing.Domain.Prices.SkuPrice", null)
                        .WithMany()
                        .HasForeignKey("SkuPriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.PricePeriodRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Pricing.Infrastructure.Persistence.ContractPriceAmendmentRow", null)
                        .WithMany()
                        .HasForeignKey("ContractPriceAmendmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UltraSol.Modules.Pricing.Domain.Prices.SkuPrice", null)
                        .WithMany()
                        .HasForeignKey("SkuPriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Pricing.Infrastructure.Persistence.PriceTierRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Pricing.Infrastructure.Persistence.PricePeriodRow", null)
                        .WithMany()
                        .HasForeignKey("PricePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}