<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../UltraSol.Modules.Inventory.Application/UltraSol.Modules.Inventory.Application.csproj" />
    <ProjectReference Include="../UltraSol.Modules.Inventory.Infrastructure/UltraSol.Modules.Inventory.Infrastructure.csproj" />
  </ItemGroup>
</Project>
