<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../UltraSol.Modules.Catalog.Application/UltraSol.Modules.Catalog.Application.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" PrivateAssets="all" />
    <ProjectReference Include="../UltraSol.Modules.Catalog.Domain/UltraSol.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\UltraSol.Shared.Infrastructure\UltraSol.Shared.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>
</Project>