// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UltraSol.Modules.Catalog.Infrastructure.Persistence;

#nullable disable

namespace UltraSol.Modules.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260907081115_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("categories", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_category_parent", "parent_category_id IS NULL OR parent_category_id <> id");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Collections.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("StoredMatchMode")
                        .HasColumnType("integer")
                        .HasColumnName("match_mode");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("collections", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_collection_type", "(type = 1 AND match_mode IS NULL) OR (type = 2 AND match_mode IS NOT NULL AND match_mode IN (1,2))");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("OptionSignature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_signature");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<bool>("StoredIsBundle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bundle");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("product_items", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItemMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasColumnType("text")
                        .HasColumnName("alt_text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ProductItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProductItemId")
                        .IsUnique()
                        .HasFilter("is_primary");

                    b.HasIndex("ProductItemId", "SortOrder");

                    b.ToTable("product_item_media", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_item_media_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsStructureLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_structure_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Status", "Id");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_status", "status IN (1,2,3,4)");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasColumnType("text")
                        .HasColumnName("alt_text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("is_primary");

                    b.HasIndex("ProductId", "SortOrder");

                    b.ToTable("product_media", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_media_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.Variation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("variations", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.VariationOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<Guid>("VariationId")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_id");

                    b.HasKey("Id");

                    b.HasIndex("VariationId");

                    b.ToTable("variation_options", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.BundleRow", b =>
                {
                    b.Property<Guid>("BundleItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("bundle_item_id");

                    b.Property<Guid>("ComponentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("BundleItemId", "ComponentItemId");

                    b.HasIndex("ComponentItemId");

                    b.ToTable("bundle_components", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_bundle_component", "quantity > 0 AND bundle_item_id <> component_item_id");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.CollectionEntryRow", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("CollectionId", "ProductId");

                    b.HasIndex("CollectionId", "SortOrder");

                    b.HasIndex("ProductId", "CollectionId");

                    b.ToTable("collection_entries", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_collection_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.ProductCategoryRow", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId", "ProductId");

                    b.ToTable("product_categories", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.RuleBrandRow", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.HasKey("CollectionId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("collection_rule_brands", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.RuleCategoryRow", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("CollectionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("collection_rule_categories", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.SelectionRow", b =>
                {
                    b.Property<Guid>("ProductItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_item_id");

                    b.Property<Guid>("VariationId")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("ProductItemId", "VariationId");

                    b.HasIndex("OptionId", "VariationId");

                    b.HasIndex("ProductItemId", "ProductId");

                    b.HasIndex("VariationId", "ProductId");

                    b.ToTable("product_item_selections", "catalog");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Categories.Category", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItem", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItemMedia", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItem", null)
                        .WithMany("Media")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Brands.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.ProductMedia", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", null)
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.Variation", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", null)
                        .WithMany("Variations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.VariationOption", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.Variation", null)
                        .WithMany("Options")
                        .HasForeignKey("VariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.BundleRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItem", null)
                        .WithMany()
                        .HasForeignKey("BundleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItem", null)
                        .WithMany()
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.CollectionEntryRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.ProductCategoryRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.RuleBrandRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Brands.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.RuleCategoryRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Infrastructure.Persistence.SelectionRow", b =>
                {
                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.VariationOption", null)
                        .WithMany()
                        .HasForeignKey("OptionId", "VariationId")
                        .HasPrincipalKey("Id", "VariationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItem", null)
                        .WithMany()
                        .HasForeignKey("ProductItemId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltraSol.Modules.Catalog.Domain.Catalog.Products.Variation", null)
                        .WithMany()
                        .HasForeignKey("VariationId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.ProductItems.ProductItem", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.Product", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Variations");
                });

            modelBuilder.Entity("UltraSol.Modules.Catalog.Domain.Catalog.Products.Variation", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
