<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8acea3cd-4fae-45cd-824c-59ce0fb299a7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Auth\UltraSol.Modules.Auth.Api\UltraSol.Modules.Auth.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Catalog\UltraSol.Modules.Catalog.Api\UltraSol.Modules.Catalog.Api.csproj" />
  </ItemGroup>

</Project>
